### ISSUE TITLE
img_201122826

### ISSUE THREAD

**Issue by ivanLM2310** [LuisEspino/CoronavirusML_2020_11#101]
![201122826](https://user-images.githubusercontent.com/26233013/99204817-69d61d80-277c-11eb-92e8-e396d0e80de2.png)

**Comment by luisespino** [comment]
¿Cuál es el comentario?

**Comment by ivanLM2310** [comment]
lo siento ingeniero, es que la utilice para poner la imagen en mi reporte, la cambiare de lugar

**Comment by luisespino** [comment]
Está bien, incluso no era necesario publicar el issue, solo era de utilizar el link. Favor de colocar la imagen en el folder img/

**Comment by ivanLM2310** [comment]
ya hice el pull request ingeniero para agregar la imagen, también le quería comentarle que  por error hice unos commit con una cuenta que tambien es mia pero la uso para el trabajo , la cuenta es **ialopezm**, hice 5 commits extras con esa cuenta
