### ISSUE TITLE
Trend of confirmed Coronavirus cases in the department of Guatemala

### ISSUE THREAD

**Issue by BernyCR96** [LuisEspino/CoronavirusML_2020_11#102]
![Practica3_201408603](https://user-images.githubusercontent.com/20645904/99204956-d05b3b80-277c-11eb-8ff3-53c40ca1c898.png)

**Comment by luisespino** [comment]
¿Cuál es el comentario?

**Comment by BernyCR96** [comment]
Buenas noches, esta imagen la utilice en mi segmento que es parte del reporte.
Creo que no había que agregarla acá, lo cambio en seguida ingeniero.

**Comment by BernyCR96** [comment]
Ya se realizo el cambio de directorio de la imagen, espero que hagan el merge y cierro este caso.
Saludos
