### ISSUE TITLE
Grado de grafico.

### ISSUE THREAD

**Issue by wilsonellolo** [LuisEspino/CoronavirusML_2020_11#35]
Considero que puede haber otro grado mas adecuado, es decir mas ajustado a la imagen, o si este esta adecuado quiza es pertinente colocar el R2 ((ajuste de la prediccion) )para visualizar que tan confiables son los datos.

El cual se puede calcular de la siguiente manera:

```` 
from sklearn.metrics import r2_score

 ( CODIGO )

r2 = r2_score(y,y_pred)

print ('R2 (ajuste de la prediccion): ' + str(r2))
````

![grrafica](https://user-images.githubusercontent.com/37234131/99012125-45c3d380-2513-11eb-9b7b-dfc598ee209c.PNG)

**Comment by DottoGC** [comment]
Definitivamente se podria seguir probando ajustar a otro grado como dice el compañero @wilsonellolo
