### ISSUE TITLE
Mapa de las redes de contagio del Covid-19

### ISSUE THREAD

**Issue by JavierHevia** [LuisEspino/CoronavirusML_2020_11#64]
![image](https://user-images.githubusercontent.com/6568351/99159945-73418600-26a7-11eb-9986-7372c29ff413.png)

https://www.agenciasinc.es/Noticias/La-genetica-traza-el-mapa-de-la-dispersion-mundial-del-virus

**Comment by luisespino** [comment]
La imágenes subirlas al folder img/
