### ISSUE TITLE
LATAM Confirmed Cases

### ISSUE THREAD

**Issue by FherHerand** [LuisEspino/CoronavirusML_2020_11#74]
![Figure_1](https://user-images.githubusercontent.com/34287415/99181391-d1945600-26f3-11eb-9b75-4491e42bc3b6.png)

![Figure_2](https://user-images.githubusercontent.com/34287415/99180350-1d8ecd00-26eb-11eb-9847-d8bdeae445bc.png)

**Comment by luisespino** [comment]
La imágenes subirlas al folder img/
