### ISSUE TITLE
Problema #covid-19-in-guatemala-cases-predictions-for-2021

### ISSUE THREAD

**Issue by luisespino** [LuisEspino/CoronavirusML_2020_11#83]
@JavierHevia en tu caso solo modelaste la tendencia, le predicción habría que definirla para x días en el futuro y verla en la gráfica. Otra cuestión es que la tendencia no debe tener un punto de inflexión al final, eso significaría que el total de contagios disminuye, cosa que no puede pasar. Saludos.

**Comment by JavierHevia** [comment]
No tenga pena, ese es el commit de hoy Ing. @LuisEspino

**Comment by JavierHevia** [comment]
Arreglado, tenía un dato erróneo el cuál era menor que el anterior y hacia el punto de inflexión. Ya subí los cambios.
